/**
 * Access gate.
 *
 * ---------------------------------------------------------------------------
 * READ THIS BEFORE RELYING ON IT
 *
 * This is a STATIC site. There is no server to authenticate against. Every file
 * that makes up this deck is downloadable by anyone who has the URL, whether or
 * not they pass this form. This gate:
 *
 *   - deters casual link-forwarding
 *   - creates a visible confidentiality marking and an acceptance step
 *   - does NOT prevent a determined viewer from reading the content
 *
 * If the deck genuinely must be restricted, put it behind a real authenticating
 * proxy (Cloudflare Access, an identity-aware proxy, or a ministry intranet).
 * See docs/SECURITY_LIMITATIONS.md — that document is not optional reading.
 * ---------------------------------------------------------------------------
 *
 * Passphrases are never stored. config/auth.config.js holds PBKDF2-SHA256
 * derivations with a per-deployment salt, generated by scripts/create-user.mjs.
 */
(function (global) {
  'use strict';

  var SESSION_KEY = 'fm.session.v1';

  var Auth = {};

  function subtleAvailable() {
    return !!(global.crypto && global.crypto.subtle && global.crypto.subtle.importKey);
  }

  /**
   * The gate is skipped when it cannot work or is not wanted:
   *  - offline/USB builds (physical possession is the control there, and
   *    crypto.subtle is not exposed on file:// in several browsers)
   *  - requireLogin turned off in presentation.config.js
   *  - no auth.config.js present (deck published without a gate)
   */
  Auth.isEnabled = function () {
    if (!global.FM.get('features.requireLogin', true)) return false;
    if (global.FM.isOffline()) return false;
    if (!global.FM_AUTH || !Array.isArray(global.FM_AUTH.users) || !global.FM_AUTH.users.length) return false;
    if (!subtleAvailable()) return false;
    return true;
  };

  Auth.disabledReason = function () {
    if (!global.FM.get('features.requireLogin', true)) return 'disabled-by-config';
    if (global.FM.isOffline()) return 'offline-build';
    if (!global.FM_AUTH || !Array.isArray(global.FM_AUTH.users) || !global.FM_AUTH.users.length) return 'no-credentials-configured';
    if (!subtleAvailable()) return 'webcrypto-unavailable';
    return null;
  };

  function toHex(buffer) {
    var bytes = new Uint8Array(buffer);
    var out = '';
    for (var i = 0; i < bytes.length; i++) {
      out += bytes[i].toString(16).padStart(2, '0');
    }
    return out;
  }

  /** PBKDF2-SHA256, matching scripts/create-user.mjs exactly. */
  Auth.derive = function (passphrase, salt, iterations) {
    var encoder = new TextEncoder();
    return global.crypto.subtle
      .importKey('raw', encoder.encode(passphrase), { name: 'PBKDF2' }, false, ['deriveBits'])
      .then(function (key) {
        return global.crypto.subtle.deriveBits(
          {
            name: 'PBKDF2',
            salt: encoder.encode(salt),
            iterations: iterations,
            hash: 'SHA-256',
          },
          key,
          256
        );
      })
      .then(toHex);
  };

  /** Constant-time-ish comparison. Timing is not a real threat here, but free. */
  function equals(a, b) {
    if (typeof a !== 'string' || typeof b !== 'string' || a.length !== b.length) return false;
    var diff = 0;
    for (var i = 0; i < a.length; i++) {
      diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
    }
    return diff === 0;
  }

  /**
   * Verifies a passphrase against every configured user rather than requiring
   * the viewer to also know which identity they are. Resolves to the matching
   * user record, or null.
   */
  Auth.verify = function (passphrase) {
    var cfg = global.FM_AUTH;
    var iterations = cfg.iterations || 310000;

    var checks = cfg.users.map(function (user) {
      return Auth.derive(passphrase, cfg.salt + ':' + user.id, iterations).then(function (hash) {
        return equals(hash, user.hash) ? user : null;
      });
    });

    return Promise.all(checks).then(function (results) {
      for (var i = 0; i < results.length; i++) {
        if (results[i]) return results[i];
      }
      return null;
    });
  };

  Auth.startSession = function (user) {
    var timeoutMs = global.FM.get('features.sessionTimeoutMinutes', 180) * 60 * 1000;
    var session = {
      userId: user.id,
      labelEn: user.labelEn || user.id,
      labelAr: user.labelAr || user.id,
      expiresAt: Date.now() + timeoutMs,
    };
    try {
      global.sessionStorage.setItem(SESSION_KEY, JSON.stringify(session));
    } catch (err) {
      // Private-browsing modes can refuse sessionStorage. The viewer will simply
      // be asked again on the next page; that is an acceptable degradation.
      return null;
    }
    return session;
  };

  Auth.getSession = function () {
    var raw;
    try {
      raw = global.sessionStorage.getItem(SESSION_KEY);
    } catch (err) {
      return null;
    }
    if (!raw) return null;

    var session;
    try {
      session = JSON.parse(raw);
    } catch (err) {
      Auth.endSession();
      return null;
    }

    if (!session || typeof session.expiresAt !== 'number' || Date.now() > session.expiresAt) {
      Auth.endSession();
      return null;
    }
    return session;
  };

  Auth.endSession = function () {
    try {
      global.sessionStorage.removeItem(SESSION_KEY);
    } catch (err) {
      /* nothing useful to do */
    }
  };

  /**
   * Called at the top of every protected page. Redirects to login.html when the
   * gate is enabled and no valid session exists.
   *
   * Returns true when the page may render.
   */
  Auth.requireSession = function () {
    if (!Auth.isEnabled()) return true;
    if (Auth.getSession()) return true;

    var here = global.location.pathname.split('/').pop() || 'index.html';
    global.location.replace('login.html?next=' + encodeURIComponent(here));
    return false;
  };

  global.FMAuth = Auth;
})(window);
