#!/usr/bin/env node
/**
 * Builds a self-contained offline copy in dist-offline/.
 *
 * The offline build is the one that actually gets presented. Ministry Wi-Fi is
 * not something to gamble a ministerial meeting on, so the USB copy is the
 * primary artifact and the hosted version is the convenience.
 *
 *   node scripts/build-offline.mjs
 *
 * Differences from the hosted build:
 *   - window.FM_OFFLINE = true is injected, which disables the access gate
 *     (physical possession of the stick is the control) and stops the deck
 *     trying to redirect to login.html from a file:// URL.
 *   - config/users.json is never copied.
 *   - node_modules, .git and CI configuration are excluded.
 */
import {
  cpSync, mkdirSync, rmSync, existsSync, readFileSync, writeFileSync, readdirSync, statSync,
} from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';
import { execFileSync } from 'node:child_process';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist-offline');

const INCLUDE_DIRS = ['assets', 'config', 'css', 'js', 'vendor', 'docs'];
const INCLUDE_FILES = [
  'index.html',
  'login.html',
  'config.html',
  'presentation-en.html',
  'presentation-ar.html',
  'README.md',
];

if (existsSync(dist)) rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });

for (const dir of INCLUDE_DIRS) {
  const from = join(root, dir);
  if (!existsSync(from)) continue;
  cpSync(from, join(dist, dir), {
    recursive: true,
    filter: (src) => !src.endsWith(`config${process.platform === 'win32' ? '\\' : '/'}users.json`),
  });
}

for (const file of INCLUDE_FILES) {
  const from = join(root, file);
  if (existsSync(from)) cpSync(from, join(dist, file));
}

// Belt and braces: never ship plaintext passphrases, whatever the filter did.
const leaked = join(dist, 'config', 'users.json');
if (existsSync(leaked)) rmSync(leaked);

/* -------------------------------------------------------------------------- */
/* Mark the build as offline                                                  */
/* -------------------------------------------------------------------------- */

const marker = `/**
 * OFFLINE BUILD MARKER — generated by scripts/build-offline.mjs
 *
 * Disables the access gate. This copy is protected by physical control of the
 * media it is on, and nothing else.
 */
window.FM_OFFLINE = true;
`;
writeFileSync(join(dist, 'config', 'offline.config.js'), marker, 'utf8');

for (const page of ['index.html', 'login.html', 'config.html', 'presentation-en.html', 'presentation-ar.html']) {
  const path = join(dist, page);
  if (!existsSync(path)) continue;
  let html = readFileSync(path, 'utf8');

  // Must load before config/presentation.config.js so FM.isOffline() is correct
  // from the very first check.
  html = html.replace(
    '<script src="config/presentation.config.js"></script>',
    '<script src="config/offline.config.js"></script>\n  <script src="config/presentation.config.js"></script>'
  );
  writeFileSync(path, html, 'utf8');
}

/* -------------------------------------------------------------------------- */
/* Report and package                                                         */
/* -------------------------------------------------------------------------- */

function totalSize(dir) {
  let bytes = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    bytes += entry.isDirectory() ? totalSize(p) : statSync(p).size;
  }
  return bytes;
}

const sizeMb = (totalSize(dist) / (1024 * 1024)).toFixed(1);
console.log('  Built dist-offline/  (' + sizeMb + ' MB)');

const zipPath = join(root, 'FarmMarshal-Offline.zip');
if (existsSync(zipPath)) rmSync(zipPath);

try {
  if (process.platform === 'win32') {
    execFileSync('powershell', [
      '-NoProfile', '-Command',
      `Compress-Archive -Path '${dist}\\*' -DestinationPath '${zipPath}' -Force`,
    ], { stdio: 'ignore' });
  } else {
    execFileSync('zip', ['-r', '-q', zipPath, '.'], { cwd: dist, stdio: 'ignore' });
  }
  console.log('  Packaged ' + relative(root, zipPath));
} catch (err) {
  console.log('  Could not create the zip automatically. Copy dist-offline/ to the USB stick directly.');
}

console.log('');
console.log('  To present: copy the folder to the stick and open index.html in Chrome or Edge.');
console.log('  Verify it on the actual presenting laptop before the meeting, not after.');
