#!/usr/bin/env node
/**
 * Copies runtime dependencies out of node_modules into vendor/ and assets/fonts/.
 *
 * The deck must run from a USB stick over file:// with no network. That rules out
 * CDNs and rules out referencing node_modules (not deployed). So everything the
 * browser needs is committed under vendor/.
 */
import { cp, mkdir, readFile, writeFile, access } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const NM = join(ROOT, 'node_modules');

const exists = async (p) => access(p).then(() => true, () => false);

/** reveal.js core + the plugins the decks actually load. */
async function vendorReveal() {
  const src = join(NM, 'reveal.js');
  if (!(await exists(src))) throw new Error('reveal.js not installed — run `npm install` first.');

  const dest = join(ROOT, 'vendor', 'reveal');
  await mkdir(dest, { recursive: true });
  await cp(join(src, 'dist'), join(dest, 'dist'), { recursive: true });

  for (const plugin of ['notes', 'zoom', 'search', 'highlight', 'markdown']) {
    const from = join(src, 'plugin', plugin);
    if (await exists(from)) {
      await cp(from, join(dest, 'plugin', plugin), { recursive: true });
    }
  }

  const version = JSON.parse(await readFile(join(src, 'package.json'), 'utf8')).version;
  console.log(`  reveal.js@${version} -> vendor/reveal/`);
  return version;
}

/**
 * Font families, with the weights we actually use. @fontsource ships every weight
 * and every subset; copying all of them would add tens of megabytes to a package
 * that has to fit on a USB stick and inside a GitHub Pages size budget.
 */
const FONTS = [
  { pkg: '@fontsource/ibm-plex-sans-arabic', family: 'IBM Plex Sans Arabic', subset: 'arabic', weights: [400, 500, 600, 700] },
  { pkg: '@fontsource/ibm-plex-sans-arabic', family: 'IBM Plex Sans Arabic', subset: 'latin', weights: [400, 500, 600, 700] },
  { pkg: '@fontsource/inter', family: 'Inter', subset: 'latin', weights: [400, 500, 600, 700] },
];

async function vendorFonts() {
  const outDir = join(ROOT, 'assets', 'fonts');
  await mkdir(join(outDir, 'files'), { recursive: true });

  const faces = [];
  for (const { pkg, family, subset, weights } of FONTS) {
    for (const weight of weights) {
      const file = `${pkg.split('/')[1]}-${subset}-${weight}-normal.woff2`;
      const from = join(NM, pkg, 'files', file);
      if (!(await exists(from))) {
        console.warn(`  ! missing ${file} — skipped`);
        continue;
      }
      await cp(from, join(outDir, 'files', file));
      faces.push(
        `@font-face {\n` +
        `  font-family: '${family}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('./files/${file}') format('woff2');\n` +
        `}`
      );
    }
  }

  const banner =
    `/* Generated by scripts/vendor-deps.mjs — do not edit by hand.\n` +
    `   Self-hosted so the deck never requests a font CDN. */\n\n`;
  await writeFile(join(outDir, 'fonts.css'), banner + faces.join('\n\n') + '\n', 'utf8');
  console.log(`  ${faces.length} font faces -> assets/fonts/fonts.css`);
  return faces.length;
}

const revealVersion = await vendorReveal();
const faceCount = await vendorFonts();

await writeFile(
  join(ROOT, 'vendor', 'VENDOR_MANIFEST.json'),
  JSON.stringify(
    { generatedAt: new Date().toISOString(), revealVersion, fontFaces: faceCount },
    null,
    2
  ) + '\n',
  'utf8'
);

console.log('Vendoring complete.');
